### PR TITLE
Update packages, README.md and a few other minor tweaks

### PR DESCRIPTION
**Pull request by sarg3nt**
- Did not update `infobloxopen/infoblox-go-client` as it has changed substantially and will require quite a bit of rework.
- Tests are currently broken.  I looked at fixing them but `kubebuilder` has changed substantially and I've never used it before and don't know what it was trying to do.
- Took the initiative to change how versioning works for the Docker image.  
  - Run `make build` to build the image then
  - Run `make push` to push the image.  This will tag the versioned image to latest and push both of them.

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
This looks promising, planned to test this webhook next week and also was looking on bumping versions first. Will let you know how it goes.

**Comment by sarg3nt** [comment]
Hi, any update on this?  Probably needs updated again at this point.

**Comment by bb-Ricardo** [comment]
There is #9 which takes care of some stuff.

**Comment by sarg3nt** [comment]
@bb-Ricardo 
OK . . but #9 also hasn't been merged.  Any plans to do that?  
Are you going to make this a priority or should we continue development on our own?

**Comment by bb-Ricardo** [comment]
Hi @sarg3nt,

This is not my repository and therefore I'm not able to merge it.

Only the owner (and other maintainers) are able to merge these PRs.

**Comment by sarg3nt** [comment]
@bb-Ricardo Sorry about that.  I meant to @ the repo owner.
@luisico Any update on this?
Thank you.

**Comment by luisico** [comment]
Hi, I no longer have access to an environment with k8s and info lox (changed position) and don't feel I can support this repo. If you would like to maintain it, I would be happy to put a notice in the readme pointing to it's successor. Sorry.

**Comment by sarg3nt** [comment]
@luisico   I'm fine with taking this over.  I'm not sure which org it's going into yet.  I have a text out to my boss to see if it should go in our corporate repo or in my personal one.   Keep this open and I'll let you know when we figure it out.

**Comment by luisico** [comment]
I added a deprecation notice in the readme. If you end up taking it over, please, let me know and I'll update with a link to the new repo. In the meantime, I'm closing all issues and pull requests and making the repo read only.

**Pull request closed without merging**
