### PR TITLE
Add possibility to configure cert duration

### PR DESCRIPTION
**Pull request by ONordander**
Hey.
This PR adds the possibility to configure the duration of the certificates which we need for our use-case.

Not sure how to bump the versions, do the app version follow the chart version? If it's incorrect just tell me how you version it and I can update.

This should be a non-breaking change as I added the previous values as default.

### CODE REVIEW

**Comment by ONordander** [comment]
@luisico could you look at this?

**Comment by luisico** [comment]
Hi @ONordander, thanks for this PR, and sorry for the late reply.

The idea sound good to me, I do have a few comments, though:

1. Add some documentation, probably under section [Install infoblox-wapi webhook](https://github.com/luisico/cert-manager-webhook-infoblox-wapi#install-infoblox-wapi-webhook).
2. I think using the `webhook` prefix in the parameters is a bit confusing. `webhook` is defined in `_helpers.tpl` as helm helper functions. I suggest to rename the parameters in `values.yaml` like:

```yaml
rootCACertificate:
  duration: "43800h"
servingCertificate:
  duration: "8760h"
```

And change their interpolation appropriately.

Other than that, looks good to me, although I haven't been able to test, and won't be able for a while (moving a couple of oceans apart at the moment!).

**Comment by ONordander** [comment]
> Hi @ONordander, thanks for this PR, and sorry for the late reply.
> 
> The idea sound good to me, I do have a few comments, though:
> 
>     1. Add some documentation, probably under section [Install infoblox-wapi webhook](https://github.com/luisico/cert-manager-webhook-infoblox-wapi#install-infoblox-wapi-webhook).
> 
>     2. I think using the `webhook` prefix in the parameters is a bit confusing. `webhook` is defined in `_helpers.tpl` as helm helper functions. I suggest to rename the parameters in `values.yaml` like:
> 
> 
> ```yaml
> rootCACertificate:
>   duration: "43800h"
> servingCertificate:
>   duration: "8760h"
> ```
> 
> And change their interpolation appropriately.
> 
> Other than that, looks good to me, although I haven't been able to test, and won't be able for a while (moving a couple of oceans apart at the moment!).

1. Done, added a section for all the values as that made more sense to me.
2. Agree, done :)

I tested it locally with `helm template -f values.yaml -n cert-manager .`

**Comment by luisico** [comment]
Thanks @ONordander, LGTM, will merge

**Comment by luisico** [comment]
@ONordander Released as 1.5.2. Let me know if you have any problems. Thanks for your help. Luis

**Comment by ONordander** [comment]
> @ONordander Released as 1.5.2. Let me know if you have any problems. Thanks for your help. Luis

Worked very well, thanks :)

**Pull request merged**
